OBJ_UNK2_OJSUBROUTINE2 := $8D31
OBJ_UNK2 := $8D09

OBJ_BANK_1B:
.addr OBJ_MYHOME_HOUSEEXIT
.addr OBJ_MYHOME_HOUSEEXIT2
.addr OBJ_MYHOME_HOUSEEXIT3
.addr OBJ_MYHOME_HOUSEEXIT4
.addr OBJ_MYHOME_HOUSEENTER
.addr OBJ_MYHOME_HOUSEENTER2
.addr OBJ_MYHOME_HOUSEENTER3
.addr OBJ_MYHOME_HOUSEENTER4
.addr OBJ_MYHOME_HOUSEENTER5


.addr OBJ_MTITOI_TEDDY
.addr OBJ_MTITOI_NOTEDDY
.addr OBJ_MTITOI_SHOP

.addr OBJ_MYHOME_PHONE

.addr OBJ_HH_NKR_DOOR
.addr OBJ_HH_EOTH_DOOR
.addr OBJ_HH_FACE_DOOR
.addr OBJ_HH_SANTA_DOOR

.addr OBJ_HH_EXIT_DOOR
.addr OBJ_HH_EXIT_DOOR2

.addr OBJ_EOTH_BOSS_FLAME_GOTTEN
.addr OBJ_NKR_BOSS_FLAME_GOTTEN
.addr OBJ_FACE_BOSS_FLAME_GOTTEN
.addr OBJ_SANTA_BOSS_FLAME_GOTTEN

.addr 0

OBJ_MYHOME_HOUSEEXIT:
objectDef OBJ_TYPE::DOOR, $26, DIRECTIONS::DOWN, $AC
doorArgDef 6, $148, DIRECTIONS::DOWN, $12E
OBJ_MYHOME_HOUSEEXIT2:
objectDef OBJ_TYPE::DOOR, $25, DIRECTIONS::DOWN, $AC
doorArgDef 6, $148, DIRECTIONS::DOWN, $12E
OBJ_MYHOME_HOUSEEXIT3:
objectDef OBJ_TYPE::DOOR, $24, DIRECTIONS::DOWN, $AC
doorArgDef 6, $148, DIRECTIONS::DOWN, $12E
OBJ_MYHOME_HOUSEEXIT4:
objectDef OBJ_TYPE::DOOR, $27, DIRECTIONS::DOWN, $AC
doorArgDef 6, $148, DIRECTIONS::DOWN, $12E

OBJ_MYHOME_HOUSEENTER:
objectDef $1f, $25, DIRECTIONS::UP, $AB
OBJ_FLAG_DISAPPEAR $26
OBJ_SUBROUTINE do_hh_entrance, 0
OBJ_STOP
OBJ_MYHOME_HOUSEENTER2:
objectDef $1f, $27, DIRECTIONS::UP, $AB
OBJ_FLAG_DISAPPEAR $26
OBJ_SUBROUTINE do_hh_entrance, 0
OBJ_STOP
OBJ_MYHOME_HOUSEENTER3:
objectDef $1f, $26, DIRECTIONS::UP, $AA
OBJ_FLAG_DISAPPEAR $26
OBJ_SUBROUTINE do_hh_entrance, 0
OBJ_STOP
OBJ_MYHOME_HOUSEENTER4:
objectDef $1f, $27, DIRECTIONS::UP, $AA
OBJ_FLAG_DISAPPEAR $26
OBJ_SUBROUTINE do_hh_entrance, 0
OBJ_STOP
OBJ_MYHOME_HOUSEENTER5:
objectDef $1f, $25, DIRECTIONS::UP, $AA
OBJ_FLAG_DISAPPEAR $26
OBJ_SUBROUTINE do_hh_entrance, 0
OBJ_STOP

do_hh_entrance:
OBJ_REMOVE_CHARACTER 4,@end-do_hh_entrance
@end:
OBJ_PLAY_MUSIC $2F
OBJ_SET_FLAG 1
OBJ_RETURN

OBJ_MYHOME_PHONE:
objectDef $19, $2a, DIRECTIONS::UP, $a0
.addr SPRITEDEF_19C ;sprite
OBJ_IS_NOT_TALKING  @JTALK0-OBJ_MYHOME_PHONE

OBJ_IS_NOT_FLAG $26, @unring-OBJ_MYHOME_PHONE
OBJ_JUMP @noring-OBJ_MYHOME_PHONE
@unring:
OBJ_SET_FLAG $26
OBJ_PLAY_MUSIC 7
@noring:

OBJ_DIALOGUE UMSG::PHONE_GRAB
OBJ_IS_NOT_FLAG $40, @firsttime-OBJ_MYHOME_PHONE

;normal routine
OBJ_DIALOGUE UMSG::PHONE_INTRO
.byte SCRIPTS::J_NONEWMONEY, @JNONEWMONEY4-OBJ_MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_NEWMONEY
      @JNONEWMONEY4:
OBJ_DIALOGUE UMSG::PHONE_NEXTLVL
.repeat 4, I
OBJ_PICK_CHARACTER_J I, @CJSELECTPARTY5-OBJ_MYHOME_PHONE
.byte SCRIPTS::GETCHARNEXTEXP
OBJ_DIALOGUE UMSG::PHONE_EXPLVL
.endrepeat
      @CJSELECTPARTY5:
OBJ_DIALOGUE UMSG::PHONE_SAVEPROMPT
OBJ_MENU UMSG::MENU_YES_NO, @JJCUSTOMMENU_26-OBJ_MYHOME_PHONE,@JJCUSTOMMENU_26-OBJ_MYHOME_PHONE
OBJ_SAVE
OBJ_DIALOGUE UMSG::PHONE_SAVED_RESETPROMPT
OBJ_MENU UMSG::MENU_CONTINUE_REST, @JJCUSTOMMENU_27-OBJ_MYHOME_PHONE,@JJCUSTOMMENU_B8-OBJ_MYHOME_PHONE
      @JJCUSTOMMENU_B8:
OBJ_DIALOGUE UMSG::PHONE_RESET_NO
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
      @JJCUSTOMMENU_27:
OBJ_DIALOGUE UMSG::PHONE_RESET_YES
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_RESET
      @JJCUSTOMMENU_26:
OBJ_DIALOGUE UMSG::PHONE_GOODLUCK
OBJ_DIALOGUE UMSG::PHONE_END
OBJ_STOP
      @firsttime:
OBJ_SET_FLAG $40
OBJ_DIALOGUE UMSG::PHONE_INTRO
OBJ_DIALOGUE UMSG::MYHOME_PHONE
OBJ_DIALOGUE UMSG::PHONE_END
      @JTALK0:
OBJ_STOP

OBJ_MTITOI_TEDDY:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $29, DIRECTIONS::DOWN, $a0
.addr SPRITEDEF_18 ;sprite
OBJ_FLAG_APPEAR 1

OBJ_IS_NOT_TALKING @end-OBJ_MTITOI_TEDDY


OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY5
OBJ_YESNO_IS_NO @no_fourth-OBJ_MTITOI_TEDDY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY6
OBJ_ADD_CHARACTER 4,@end-OBJ_MTITOI_TEDDY
OBJ_CLEAR_FLAG 1
OBJ_STOP
@no_fourth:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY7
    @end:
OBJ_STOP

OBJ_MTITOI_NOTEDDY:
objectDef $1F, $29, DIRECTIONS::DOWN, $a0
OBJ_FLAG_DISAPPEAR 1

OBJ_IS_NOT_TOUCHING @end-OBJ_MTITOI_NOTEDDY

OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY5
OBJ_YESNO_IS_NO @no_fourth-OBJ_MTITOI_NOTEDDY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY6
OBJ_STOP
@no_fourth:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY7
OBJ_REMOVE_CHARACTER 4,@end-OBJ_MTITOI_NOTEDDY
OBJ_SET_FLAG 1
    @end:
OBJ_STOP

OBJ_MTITOI_SHOP:
objectDef OBJ_TYPE::STATIONARY_NPC, $21, DIRECTIONS::DOWN, $a0
.addr SPRITEDEF_183 ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_MTITOI_SHOP
OBJ_DIALOGUE UMSG::MTITOI_HEALERFAIL
OBJ_MENU UMSG::HEALER, @Heal-OBJ_MTITOI_SHOP,@Exit-OBJ_MTITOI_SHOP
@Shop:
OBJ_DIALOGUE UMSG::MTITOI_HEALER
OBJ_SET_FLAG 11
@shop_loop:
OBJ_NOT_HAS_ITEM 0, @no_room-OBJ_MTITOI_SHOP ;has space?
OBJ_DISPLAY_ITEMS 60, 61, 63, 65, @Exit-OBJ_MTITOI_SHOP
OBJ_TAKE_MONEY @no_money-OBJ_MTITOI_SHOP
OBJ_SHOW_MONEY
OBJ_PLAY_SOUND $0b
OBJ_GIVE_ITEM @no_room-OBJ_MTITOI_SHOP
OBJ_DIALOGUE $03e3
OBJ_YESNO_IS_NO @end-OBJ_MTITOI_SHOP
OBJ_JUMP @shop_loop-OBJ_MTITOI_SHOP


OBJ_STOP

@Heal:
OBJ_DIALOGUE UMSG::MAGICANT_GUITARMAN_SONG
.repeat 4, I
OBJ_PICK_CHARACTER_J I, @end-OBJ_MTITOI_SHOP
OBJ_HEAL $FF
OBJ_PPHEAL $FF
OBJ_AND_STATUS 0
OBJ_PLAY_SOUND $7
OBJ_DELAY $20
.endrepeat

OBJ_STOP

@no_money:
OBJ_DIALOGUE UMSG::MYHOME_MOM_EAT
OBJ_JUMP @end-OBJ_MTITOI_SHOP

@no_room:
OBJ_DIALOGUE UMSG::MERRYSVILLE_TRAINWOMAN
OBJ_JUMP @end-OBJ_MTITOI_SHOP

@Exit:
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY7
    @end:
OBJ_CLEAR_FLAG 11
OBJ_STOP

OBJ_HH_NKR_DOOR:
objectDef OBJ_TYPE::DOOR, $2e, DIRECTIONS::RIGHT, $a2
doorArgDef 7, 1, DIRECTIONS::RIGHT, $b7
OBJ_HH_EOTH_DOOR:
objectDef OBJ_TYPE::DOOR, $19, DIRECTIONS::LEFT, $a6
doorArgDef 7, $59, DIRECTIONS::LEFT, $8a
OBJ_HH_FACE_DOOR:
objectDef OBJ_TYPE::DOOR, $19, DIRECTIONS::LEFT, $96
doorArgDef 7, $d, DIRECTIONS::LEFT, $86
OBJ_HH_SANTA_DOOR:
objectDef OBJ_TYPE::DOOR, $36, DIRECTIONS::RIGHT, $9a
doorArgDef 7, $72, DIRECTIONS::RIGHT, $8a

OBJ_EOTH_BOSS_FLAME_GOTTEN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $23, DIRECTIONS::UP, $91
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_APPEAR $f7
OBJ_STOP

OBJ_NKR_BOSS_FLAME_GOTTEN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $28, DIRECTIONS::UP, $91
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_APPEAR $f6
OBJ_STOP

OBJ_FACE_BOSS_FLAME_GOTTEN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $22, DIRECTIONS::UP, $92
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_APPEAR $f5
OBJ_STOP

OBJ_SANTA_BOSS_FLAME_GOTTEN:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, $29, DIRECTIONS::UP, $92
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_APPEAR $f4
OBJ_STOP


OBJ_HH_EXIT_DOOR:
objectDef $1B, $25, DIRECTIONS::RIGHT, $93
OBJ_IS_NOT_TOUCHING @end-OBJ_HH_EXIT_DOOR
OBJ_IS_NOT_FLAG 2, @end-OBJ_HH_EXIT_DOOR
OBJ_TELEPORT $3f, $a5, DIRECTIONS::UP, $df
@end:
OBJ_STOP

OBJ_HH_EXIT_DOOR2:
objectDef $1B, $26, DIRECTIONS::RIGHT, $93
OBJ_IS_NOT_TOUCHING @end-OBJ_HH_EXIT_DOOR2
OBJ_IS_NOT_FLAG 2, @end-OBJ_HH_EXIT_DOOR2
OBJ_TELEPORT $3f, $a6, DIRECTIONS::UP, $df
@end:
OBJ_STOP

.align $675 ;because we havent disassembled other banks LOL