OBJ_BANK_6:
.addr OBJ_HORROR_TRIGGER_1
.addr OBJ_HORROR_TRIGGER_2
.addr 0


OBJ_HORROR_TRIGGER_1:
objectDef $1B, $a6, DIRECTIONS::RIGHT, $b4
OBJ_IS_NOT_TOUCHING @end-OBJ_HORROR_TRIGGER_1
OBJ_BATTLE (BATTLE_HORROR-BATTLES_START)/$A
.byte $6b
@end:
OBJ_STOP

OBJ_HORROR_TRIGGER_2:
objectDef $1B, $a5, DIRECTIONS::RIGHT, $b4
OBJ_IS_NOT_TOUCHING @end-OBJ_HORROR_TRIGGER_2
OBJ_BATTLE (BATTLE_HORROR-BATTLES_START)/$A
.byte $6b
@end:
OBJ_STOP