OBJ_BANK_B:
.addr OBJ_PODUNK_MERRYCOP
.addr OBJ_PODUNK_MERRYCOP2
.addr 0

OBJ_PODUNK_MERRYCOP:
objectDef OBJ_TYPE::STATIONARY_NPC, $d2, DIRECTIONS::DOWN, $16e
.addr SPRITEDEF_72 ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MERRYCOP
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION_FIGHT
    @JTALK0:
OBJ_STOP

OBJ_PODUNK_MERRYCOP2:
objectDef OBJ_TYPE::STATIONARY_NPC, $d4, DIRECTIONS::DOWN, $16e
.addr SPRITEDEF_72 ;sprite
OBJ_IS_NOT_TALKING @JTALK0-OBJ_PODUNK_MERRYCOP2
OBJ_DIALOGUE UMSG::MYHOME_MINNIE_INVASION_FIGHT_2
    @JTALK0:
OBJ_STOP