OBJ_BANK_7:

;eoth
;;lobby
.addr OBJ_EOTH_HH_DOOR
.addr OBJ_EOTH_EOTHC_DOOR
.addr OBJ_EOTH_NEUTRALGUY
.addr OBJ_EOTH_LOVEGIRL
.addr OBJ_EOTH_HATEGUY
.addr OBJ_EOTH_SKEEGUY
.addr OBJ_EOTH_DUNKGUY
.addr OBJ_EOTH_WEAPONGUY
.addr OBJ_EOTH_WEAPON
.addr OBJ_EOTH_TRENDGUY

;;corn maize
.addr OBJ_EOTH_EXIT_SIGN
.addr OBJ_EOTH_HINT_SIGN
.addr OBJ_EOTH_PRESENT1
.addr OBJ_EOTH_PRESENT2
.addr OBJ_EOTH_LOSTGUY
.addr OBJ_EOTH_GIRLGUY
.addr OBJ_EOTH_GUYGIRL

;;boss
.addr OBJ_EOTH_BOSS
.addr OBJ_EOTH_BOSS_FLAME
.addr OBJ_EOTH_EXIT
.addr 0

;eoth
OBJ_EOTH_HH_DOOR:
objectDef OBJ_TYPE::DOOR, $5a, DIRECTIONS::RIGHT, $8a
doorArgDef 7, $1a, DIRECTIONS::RIGHT, $a6
OBJ_EOTH_EOTHC_DOOR:
objectDef OBJ_TYPE::DOOR, $41, DIRECTIONS::LEFT, $96
doorArgDef 7, $5a, DIRECTIONS::LEFT, $c8

OBJ_EOTH_NEUTRALGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $4f, DIRECTIONS::DOWN, $88
.addr SPRITEDEF_ROBOT ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_NEUTRALGUY
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL3
    @end:
OBJ_STOP

OBJ_EOTH_LOVEGIRL:
objectDef OBJ_TYPE::SPINNING_NPC, $50, DIRECTIONS::DOWN, $88
.addr SPRITEDEF_CLOWN ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_LOVEGIRL
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL4
    @end:
OBJ_STOP

OBJ_EOTH_HATEGUY:
objectDef OBJ_TYPE::SPINNING_NPC, $51, DIRECTIONS::DOWN, $88
.addr SPRITEDEF_DRACULA ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_HATEGUY
OBJ_DIALOGUE UMSG::PODUNK_MAYORGUY
    @end:
OBJ_STOP

OBJ_EOTH_SKEEGUY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $55, DIRECTIONS::DOWN, $8d
.addr SPRITEDEF_DINOSAUR ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_SKEEGUY
OBJ_DIALOGUE UMSG::PODUNK_CONCERNEDGUY
    @end:
OBJ_STOP

OBJ_EOTH_DUNKGUY:
objectDef OBJ_TYPE::WANDERINGFAST_NPC, $4c, DIRECTIONS::DOWN, $95
.addr SPRITEDEF_SCREAMER ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_DUNKGUY
OBJ_DIALOGUE UMSG::PODUNK_SENSIBLEGUY1
    @end:
OBJ_STOP

OBJ_EOTH_WEAPONGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $55, DIRECTIONS::DOWN, $96
.addr SPRITEDEF_WOLF ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_WEAPONGUY
OBJ_DIALOGUE UMSG::PODUNK_SENSIBLEGUY2
    @end:
OBJ_STOP

OBJ_EOTH_WEAPON:
objectDef $20, $57, 0, $98
.addr SPRITEDEF_PRESENT ;sprite
.byte 35 ;item
.byte $ef ;flag

OBJ_EOTH_TRENDGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $48, DIRECTIONS::DOWN, $94
.addr SPRITEDEF_WOLF ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_TRENDGUY
OBJ_DIALOGUE UMSG::PODUNK_EVENTGIRL1
.byte SCRIPTS::REGNAME
OBJ_DIALOGUE UMSG::PODUNK_EVENTGIRL2
    @end:
OBJ_STOP

;;corn maize
OBJ_EOTH_EXIT_SIGN:
objectDef $19, $47, 0, $ca
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @END1-OBJ_EOTH_EXIT_SIGN
OBJ_DIALOGUE UMSG::PODUNK_ZOMBIE
OBJ_STOP
    @END1:
OBJ_IS_NOT_TALKING @END-OBJ_EOTH_EXIT_SIGN
OBJ_DIALOGUE UMSG::PODUNK_ZOMBIE2
OBJ_TELEPORT 7, $d, DIRECTIONS::LEFT, $aa
    @END:
OBJ_STOP

OBJ_EOTH_HINT_SIGN:
objectDef $19, $5c, 0, $a3
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @END1-OBJ_EOTH_HINT_SIGN
OBJ_DIALOGUE UMSG::PODUNK_NECROMANCERWOMAN1
OBJ_STOP
    @END1:
OBJ_IS_NOT_TALKING @END-OBJ_EOTH_HINT_SIGN
OBJ_DIALOGUE UMSG::PODUNK_NECROMANCERWOMAN2
    @END:
OBJ_STOP


OBJ_EOTH_LOSTGUY:
objectDef OBJ_TYPE::SPINNING_NPC, $40, DIRECTIONS::DOWN, $c2
.addr SPRITEDEF_ROBOT ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_LOSTGUY
OBJ_DIALOGUE UMSG::PODUNK_WARYGUY
    @end:
OBJ_STOP

OBJ_EOTH_GIRLGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $50, DIRECTIONS::DOWN, $b6
.addr SPRITEDEF_WOLF ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_GIRLGUY
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL1
    @end:
OBJ_STOP

OBJ_EOTH_GUYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $43, DIRECTIONS::DOWN, $a7
.addr SPRITEDEF_CLOWN ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_GUYGIRL
OBJ_DIALOGUE UMSG::PODUNK_CANARYGIRL2
    @end:
OBJ_STOP

OBJ_EOTH_PRESENT1:
objectDef $20, $46, 0, $a2
.addr SPRITEDEF_PRESENT ;sprite
.byte 34 ;item
.byte $ee ;flag
OBJ_EOTH_PRESENT2:
objectDef $20, $44, 0, $c0
.addr SPRITEDEF_PRESENT ;sprite
.byte 4 ;item
.byte $ed ;flag

;;boss
OBJ_EOTH_BOSS:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 8, DIRECTIONS::DOWN, $a8
.addr SPRITEDEF_CLOWN ;sprite
OBJ_FLAG_DISAPPEAR $f7
OBJ_IS_NOT_TALKING @end-OBJ_EOTH_BOSS
OBJ_DIALOGUE UMSG::PODUNK_POLTERGUY
OBJ_BATTLE (BATTLE_EOTH-BATTLES_START)/$A
OBJ_SET_FLAG $f7
OBJ_SUBROUTINE obj_bossfinisher_subr, 0
    @end:
OBJ_STOP

OBJ_EOTH_BOSS_FLAME:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 7, DIRECTIONS::UP, $a6
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_DISAPPEAR $f7
    @end:
OBJ_STOP

OBJ_EOTH_EXIT:
objectDef OBJ_TYPE::DOOR, 1, DIRECTIONS::LEFT, $aa
doorArgDef 7, $25, DIRECTIONS::DOWN, $a5

