
;debating on whether or not to give every single npc a unique name.
;we'll see

OBJ_BANK_2:
.addr OBJ_PODUNK_CEMETERYGUY
.addr OBJ_PODUNK_SCAREDGUY
.addr OBJ_PODUNK_NECROMANCERWOMAN
.addr OBJ_PODUNK_WARYGUY
.addr OBJ_PODUNK_CANARYGIRL
.addr OBJ_PODUNK_MAYORGUY
.addr OBJ_PODUNK_CONCERNEDGUY
.addr OBJ_PODUNK_SENSIBLEGUY
.addr OBJ_PODUNK_EVENTGIRL
.addr OBJ_PODUNK_POLTERGUY
.addr OBJ_PODUNK_ZOOGUY
.addr OBJ_PODUNK_SIGN
.addr OBJ_GRAVEYARD_CHURCHENTRANCE

.addr 0



;snickersguy
OBJ_PODUNK_CEMETERYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $f0, 4, $150
.addr SPRITEDEF_WOLF ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_CEMETERYGUY
OBJ_DIALOGUE UMSG::MYHOME_JUICE
    @END:
OBJ_STOP

;brotherclowngirl
OBJ_PODUNK_SCAREDGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $f8, 4, $156
.addr SPRITEDEF_CLOWN ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_SCAREDGUY
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE_INVASION
    @END:
OBJ_STOP

;dogguy
OBJ_PODUNK_NECROMANCERWOMAN:
objectDef OBJ_TYPE::WANDERING_NPC, $100, 4, $153
.addr SPRITEDEF_DRACULA ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_NECROMANCERWOMAN
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE_INVASION_FIGHT
    @END:
OBJ_STOP

;boogirl
OBJ_PODUNK_WARYGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $110, 4, $15a
.addr SPRITEDEF_SCREAMER ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_WARYGUY
OBJ_DIALOGUE UMSG::MYHOME_MIMMIE
    @END:
OBJ_STOP

;canihavecandy
OBJ_PODUNK_CANARYGIRL:
objectDef OBJ_TYPE::WANDERING_NPC, $10a, 4, $15b
.addr SPRITEDEF_ROBOT ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_CANARYGIRL
OBJ_DIALOGUE UMSG::MYHOME_MOM_INVASION
OBJ_YESNO_IS_NO  @JYESNO2-OBJ_PODUNK_CANARYGIRL
OPJ_LOAD_NUMBER 1
OBJ_TAKE_MONEY @nomoney-OBJ_PODUNK_CANARYGIRL
OBJ_DIALOGUE UMSG::MYHOME_MOM_HURT
OBJ_STOP
@nomoney:
OBJ_DIALOGUE UMSG::MYHOME_MOM_EAT
OBJ_STOP
    @JYESNO2:
OBJ_DIALOGUE UMSG::MYHOME_MOM
    @END:
OBJ_STOP

;dinokid
OBJ_PODUNK_MAYORGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $117, DIRECTIONS::LEFT, $153
.addr SPRITEDEF_DINOSAUR ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_MAYORGUY
OBJ_DIALOGUE UMSG::PODUNK_PIPPIMOM_THANKS
    @END:
OBJ_STOP

;wolfbro
OBJ_PODUNK_CONCERNEDGUY:
objectDef OBJ_TYPE::STATIONARY_NPC, $116, DIRECTIONS::RIGHT, $153
.addr SPRITEDEF_WOLF ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_CONCERNEDGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY1
    @END:
OBJ_STOP

;existguy
OBJ_PODUNK_SENSIBLEGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $110, DIRECTIONS::RIGHT, $148
.addr SPRITEDEF_DRACULA ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_SENSIBLEGUY
OBJ_DIALOGUE UMSG::PODUNK_CEMETERYGUY2
    @END:
OBJ_STOP

;eggman
OBJ_PODUNK_EVENTGIRL:
objectDef OBJ_TYPE::STATIONARY_NPC, $10D, DIRECTIONS::DOWN, $138
.addr SPRITEDEF_MAN ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_EVENTGIRL
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY1
    @END:
OBJ_STOP

;clownscared
OBJ_PODUNK_POLTERGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $11d, DIRECTIONS::RIGHT, $13c
.addr SPRITEDEF_CLOWN ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_POLTERGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY2
    @END:
OBJ_STOP

;lastdino
OBJ_PODUNK_ZOOGUY:
objectDef OBJ_TYPE::WANDERING_NPC, $12d, DIRECTIONS::RIGHT, $13c
.addr SPRITEDEF_DINOSAUR ;sprite
OBJ_IS_NOT_TALKING @END-OBJ_PODUNK_ZOOGUY
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY3
    @END:
OBJ_STOP

OBJ_PODUNK_SIGN:
objectDef $19, $147, DIRECTIONS::UP, $12e
.addr SPRITEDEF_65 ;sprite
OBJ_IS_NOT_CHECKING @JCHECK0-OBJ_PODUNK_SIGN
OBJ_DIALOGUE UMSG::PODUNK_SCAREDGUY4
    @JCHECK0:
OBJ_STOP

OBJ_GRAVEYARD_CHURCHENTRANCE:
objectDef OBJ_TYPE::DOOR, $148, DIRECTIONS::UP, $12d
doorArgDef 7, $26, DIRECTIONS::UP, $AB



