OBJ_BANK_4:
.addr OBJ_FACE_HH_DOOR
.addr OBJ_FACE_FAILDOOR1
.addr OBJ_FACE_DOOR1

.addr OBJ_FACE_DOOR2
.addr OBJ_FACE_FAILDOOR2
.addr OBJ_FACE_FAILDOOR3
.addr OBJ_FACE_DOOR3
.addr OBJ_FACE_DOOR32
.addr OBJ_FACE_DOOR33
.addr OBJ_FACE_HINT_SIGN
.addr OBJ_test0
.addr OBJ_test1
.addr OBJ_test2
.addr OBJ_test3
.addr OBJ_test4
.addr OBJ_test5
.addr OBJ_test6

.addr OBJ_FACE_EXIT
.addr OBJ_FACE_EXIT2

.addr OBJ_FACE_dfix
.addr OBJ_MYHOME_DOLL_INVASION
.addr OBJ_MYHOME_DOLL_INVASION2
.addr OBJ_MYHOME_DOLL_INVASION3
.addr OBJ_FACE_FUNNY



.addr 0

OBJ_FACE_HH_DOOR:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $86
doorArgDef 7, $1a, DIRECTIONS::RIGHT, $96

OBJ_FACE_FAILDOOR1:
objectDef OBJ_TYPE::DOOR, 0, DIRECTIONS::LEFT, $87
doorArgDef 7, $d, DIRECTIONS::LEFT, $86
OBJ_FACE_DOOR1:
objectDef OBJ_TYPE::DOOR, 2, DIRECTIONS::LEFT, $85
doorArgDef 7, $5d, DIRECTIONS::LEFT, $ee

OBJ_FACE_DOOR2:
objectDef OBJ_TYPE::DOOR, $5e, DIRECTIONS::RIGHT, $ee
doorArgDef 7, $6d, DIRECTIONS::LEFT, $a6
OBJ_FACE_FAILDOOR2:
objectDef OBJ_TYPE::DOOR, $50, DIRECTIONS::LEFT, $ef
doorArgDef 7, $5d, DIRECTIONS::LEFT, $ee
OBJ_FACE_FAILDOOR3:
objectDef OBJ_TYPE::DOOR, $52, DIRECTIONS::LEFT, $ed
doorArgDef 7, $1a, DIRECTIONS::RIGHT, $96

OBJ_FACE_DOOR3:
objectDef OBJ_TYPE::DOOR, $6e, DIRECTIONS::RIGHT, $a6
doorArgDef 7, $72, DIRECTIONS::RIGHT, $b6
OBJ_FACE_DOOR32:
objectDef OBJ_TYPE::DOOR, $60, DIRECTIONS::LEFT, $a7
doorArgDef 7, $72, DIRECTIONS::RIGHT, $b6
OBJ_FACE_DOOR33:
objectDef OBJ_TYPE::DOOR, $62, DIRECTIONS::LEFT, $a5
doorArgDef 7, $72, DIRECTIONS::RIGHT, $b6

OBJ_FACE_HINT_SIGN:
objectDef $19, $67, 0, $a6
.addr SPRITEDEF_SIGN ;sprite
OBJ_IS_NOT_CHECKING @END1-OBJ_FACE_HINT_SIGN
OBJ_DIALOGUE UMSG::GRAVEYARD_PIPPI
    @END1:
OBJ_STOP

.define OBJ_TYPE_SHOWTEXTSEE $2E

OBJ_test0:
objectDef OBJ_TYPE_SHOWTEXTSEE, $67, DIRECTIONS::DOWN, $a6
OBJ_FLAG_APPEAR $a0
OBJ_CLEAR_FLAG $a0
OBJ_CLEAR_FLAG $a1
OBJ_CLEAR_FLAG $a2
OBJ_CLEAR_FLAG $a3
OBJ_CLEAR_FLAG $a4
OBJ_STOP

OBJ_test1:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $d0
OBJ_FLAG_DISAPPEAR $a0
OBJ_IS_NOT_FLAG $f5, @end-OBJ_test1
OBJ_SET_FLAG $a0
OBJ_STOP
@end:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_BRAVE_YES
OBJ_SET_FLAG $a0
OBJ_STOP

OBJ_test2:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $c8
OBJ_FLAG_DISAPPEAR $a1
OBJ_IS_NOT_FLAG $f5, @end-OBJ_test2
OBJ_SET_FLAG $a1
OBJ_STOP
@end:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_BRAVE_NO
OBJ_SET_FLAG $a1
OBJ_STOP

OBJ_test3:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $c0
OBJ_FLAG_DISAPPEAR $a2
OBJ_IS_NOT_FLAG $f5, @end-OBJ_test3
OBJ_SET_FLAG $a2
OBJ_STOP
@end:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_YES
OBJ_SET_FLAG $a2
OBJ_STOP

OBJ_test4:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $b8
OBJ_FLAG_DISAPPEAR $a3
OBJ_IS_NOT_FLAG $f5, @end-OBJ_test4
OBJ_SET_FLAG $a3
OBJ_STOP
@end:
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NO
OBJ_SET_FLAG $a3
OBJ_STOP

OBJ_test5:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $b2
OBJ_FLAG_DISAPPEAR $a4
OBJ_IS_NOT_FLAG $f5, @end-OBJ_test5
OBJ_SET_FLAG $a4
OBJ_STOP
@end:
OBJ_DIALOGUE UMSG::ZOO_GATEMONKEY
OBJ_SET_FLAG $a4
OBJ_BATTLE (BATTLE_FACE-BATTLES_START)/$A
OBJ_STOP

OBJ_test6:
objectDef OBJ_TYPE_SHOWTEXTSEE, $64, DIRECTIONS::DOWN, $b0
OBJ_FLAG_DISAPPEAR $f5
OBJ_SET_FLAG $f5
OBJ_SUBROUTINE obj_bossfinisher_subr, 0
OBJ_STOP

OBJ_FACE_EXIT:
objectDef OBJ_TYPE::DOOR, $63, DIRECTIONS::UP, $b3
doorArgDef 7, $25, DIRECTIONS::DOWN, $a5
OBJ_FACE_EXIT2:
objectDef OBJ_TYPE::DOOR, $64, DIRECTIONS::UP, $b3
doorArgDef 7, $25, DIRECTIONS::DOWN, $a5

OBJ_FACE_dfix:
objectDef OBJ_TYPE::DOOR, $8e, DIRECTIONS::RIGHT, $b6
doorArgDef 7, $58, DIRECTIONS::RIGHT, $db

OBJ_MYHOME_DOLL_INVASION:
objectDef $16, $7c, DIRECTIONS::UP, $b6
.addr SPRITEDEF_MOVING_COFFIN ;sprite
OBJ_FLAG_DISAPPEAR $d0
OBJ_IS_NOT_TOUCHING @end-OBJ_MYHOME_DOLL_INVASION
OBJ_DIALOGUE UMSG::CANARY_PILLAR
OBJ_BATTLE (BATTLE_WRAITHS-BATTLES_START)/$A
OBJ_SET_FLAG $d0
@end:
OBJ_STOP

OBJ_MYHOME_DOLL_INVASION2:
objectDef $16, $80, DIRECTIONS::UP, $b5
.addr SPRITEDEF_MOVING_COFFIN ;sprite
OBJ_FLAG_DISAPPEAR $d1
OBJ_IS_NOT_TOUCHING @end-OBJ_MYHOME_DOLL_INVASION2
OBJ_DIALOGUE UMSG::CANARY_PILLAR
OBJ_BATTLE (BATTLE_HEART-BATTLES_START)/$A
OBJ_SET_FLAG $d1
@end:
OBJ_STOP

OBJ_MYHOME_DOLL_INVASION3:
objectDef $16, $83, DIRECTIONS::UP, $b7
.addr SPRITEDEF_MOVING_COFFIN ;sprite
OBJ_FLAG_DISAPPEAR $d2
OBJ_IS_NOT_TOUCHING @end-OBJ_MYHOME_DOLL_INVASION3
OBJ_DIALOGUE UMSG::CANARY_PILLAR
OBJ_BATTLE (BATTLE_STINKYGHOST-BATTLES_START)/$A
OBJ_SET_FLAG $d2
@end:
OBJ_STOP

OBJ_FACE_FUNNY:
objectDef OBJ_TYPE::STATIONARY_NPC, $7e, DIRECTIONS::DOWN, $b4
.addr SPRITEDEF_LEGAL ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_FACE_FUNNY
OBJ_DIALOGUE UMSG::CANARY_GENERIC
@end:
OBJ_STOP