OBJ_BANK_3:
;nkr
.addr OBJ_NKR_HH_DOOR
.addr OBJ_NKR_Q1
.addr OBJ_NKR_Q2
.addr OBJ_NKR_Q3
.addr OBJ_NKR_Q4
.addr OBJ_NKR_Q5
.addr OBJ_NKR_Q6

.addr OBJ_NKR_DOOR2
.addr OBJ_NKR_DOOR2BACK
.addr OBJ_NKR_PRESENT1
.addr OBJ_NKR_PRESENT2
.addr OBJ_NKR_DOOR3
.addr OBJ_NKR_DOOR3BACK
.addr OBJ_NKR_PRESENT3
.addr OBJ_NKR_PRESENT4
.addr OBJ_NKR_DOOR4
.addr OBJ_NKR_DOOR4BACK
.addr OBJ_NKR_BOSS
.addr OBJ_NKR_BOSS_FLAME
.addr OBJ_NKR_EXIT
.addr 0

;nkr
OBJ_NKR_HH_DOOR:
objectDef OBJ_TYPE::DOOR, 0, DIRECTIONS::LEFT, $b7
doorArgDef 7, $2d, DIRECTIONS::LEFT, $a2

.define OBJ_DISPLAY_ITEMS2(item1, item2, item3, item4, label) .byte $6A, item1, item2, item3, item4, label

;2 4 6
OBJ_NKR_Q1:
objectDef OBJ_TYPE::STATIONARY_NPC, 5, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q1
OBJ_DIALOGUE UMSG::PODUNK_ZOOGUY
OBJ_DISPLAY_ITEMS2 $80, $81, $82, 0, @end-OBJ_NKR_Q1
OBJ_IS_NOT_SELECTED $81, @wrong-OBJ_NKR_Q1
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_MOVE question_mover
OBJ_MOVE question_mover2
OBJ_STOP
    @wrong:
    OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    @end:
OBJ_STOP

question_mover:
moveDef DIRECTIONS::DOWN, MOVE_CMD::ABOUTFACE, 1
moveDef DIRECTIONS::UP, MOVE_CMD::MOVE, 2
OBJ_RETURN
question_mover2:
OBJ_STOP

;2 4 8
OBJ_NKR_Q2:
objectDef OBJ_TYPE::STATIONARY_NPC, 10, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q2
OBJ_DIALOGUE UMSG::TWINKLE_LLOYDBULLY2_LLOYD
OBJ_DISPLAY_ITEMS2 $80, $81, $83, 0, @end-OBJ_NKR_Q2
OBJ_IS_NOT_SELECTED $81, @wrong-OBJ_NKR_Q2
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_MOVE question_mover
OBJ_MOVE question_mover2
OBJ_STOP
    @wrong:
    OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    @end:
OBJ_STOP

;3 4 5
OBJ_NKR_Q3:
objectDef OBJ_TYPE::STATIONARY_NPC, 15, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q3
OBJ_DIALOGUE UMSG::REINDEER_DRAGONGIRL_CHECK
OBJ_DISPLAY_ITEMS2 $84, $81, $85, 0, @end-OBJ_NKR_Q3
OBJ_IS_NOT_SELECTED $81, @wrong-OBJ_NKR_Q3
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_MOVE question_mover
OBJ_MOVE question_mover2
OBJ_STOP
    @wrong:
    OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    @end:
OBJ_STOP

;Idk 4 12
OBJ_NKR_Q4:
objectDef OBJ_TYPE::STATIONARY_NPC, 20, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q4
OBJ_DIALOGUE UMSG::PODUNK_CASHCARDWOMAN
OBJ_DISPLAY_ITEMS2 $89, $81, $86, 0, @end-OBJ_NKR_Q4
OBJ_IS_NOT_SELECTED $81, @wrong-OBJ_NKR_Q4
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_MOVE question_mover
OBJ_MOVE question_mover2
OBJ_STOP
    @wrong:
    OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    @end:
OBJ_STOP

;Yes 4 No
OBJ_NKR_Q5:
objectDef OBJ_TYPE::STATIONARY_NPC, 25, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q5
OBJ_DIALOGUE UMSG::CANARY_MAN
OBJ_DISPLAY_ITEMS2 $8A, $81, $8B, 0, @end-OBJ_NKR_Q5
OBJ_DIALOGUE UMSG::PODUNK_PIPPI_MEET_NOYES
OBJ_MOVE question_mover
OBJ_MOVE question_mover2
    @end:
OBJ_STOP

;3.14 4 13
OBJ_NKR_Q6:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 30, DIRECTIONS::LEFT, $b7
.addr SPRITEDEF_ZAMBIE ;sprite
OBJ_FLAG_DISAPPEAR $c0

OBJ_IS_NOT_CASTING 1, @checktalk-OBJ_NKR_Q6

OBJ_DIALOGUE UMSG::CANARY_MAN_BABY_NO
OBJ_BATTLE (BATTLE_ZAMBIES-BATTLES_START)/$A
OBJ_SET_FLAG $c0

@checktalk:
OBJ_IS_NOT_TALKING @end-OBJ_NKR_Q6
OBJ_DIALOGUE UMSG::CANARY_MAN_BABY
OBJ_DISPLAY_ITEMS2 $87, $81, $88, 0, @wrong-OBJ_NKR_Q6
    @wrong:
    OBJ_DIALOGUE UMSG::PODUNK_BREADGIRL
    @end:
OBJ_STOP

OBJ_NKR_DOOR2:
objectDef OBJ_TYPE::DOOR, $1f, DIRECTIONS::RIGHT, $b7
doorArgDef 7, $39, DIRECTIONS::LEFT, $ba
OBJ_NKR_DOOR2BACK:
objectDef OBJ_TYPE::DOOR, $3a, DIRECTIONS::RIGHT, $ba
doorArgDef 7, $1e, DIRECTIONS::LEFT, $b7

OBJ_NKR_PRESENT1:
objectDef $20, $32, 0, $cd
.addr SPRITEDEF_PRESENT ;sprite
.byte 34 ;item
.byte $ec ;flag
OBJ_NKR_PRESENT2:
objectDef $20, $3a, 0, $c4
.addr SPRITEDEF_PRESENT ;sprite
.byte 38 ;item
.byte $eb ;flag

OBJ_NKR_DOOR3:
objectDef OBJ_TYPE::DOOR, $2d, DIRECTIONS::LEFT, $c6
doorArgDef 7, $21, DIRECTIONS::LEFT, $d2
OBJ_NKR_DOOR3BACK:
objectDef OBJ_TYPE::DOOR, $22, DIRECTIONS::RIGHT, $d2
doorArgDef 7, $2e, DIRECTIONS::RIGHT, $c6

OBJ_NKR_PRESENT3:
objectDef $20, $18, 0, $d2
.addr SPRITEDEF_PRESENT ;sprite
.byte 37 ;item
.byte $ea ;flag
OBJ_NKR_PRESENT4:
objectDef $20, $10, 0, $df
.addr SPRITEDEF_PRESENT ;sprite
.byte 40 ;item
.byte $e9 ;flag

OBJ_NKR_DOOR4:
objectDef OBJ_TYPE::DOOR, 1, DIRECTIONS::LEFT, $d6
doorArgDef 7, $d, DIRECTIONS::LEFT, $c6
OBJ_NKR_DOOR4BACK:
objectDef OBJ_TYPE::DOOR, $e, DIRECTIONS::RIGHT, $c6
doorArgDef 7, 2, DIRECTIONS::RIGHT, $d6

;;boss
OBJ_NKR_BOSS:
objectDef OBJ_TYPE::STATIONARY_NPC, 6, DIRECTIONS::DOWN, $c4
.addr SPRITEDEF_Nathan ;sprite
OBJ_IS_NOT_TALKING @end-OBJ_NKR_BOSS

OBJ_IS_NOT_FLAG $f6, @nokill-OBJ_NKR_BOSS
OBJ_DIALOGUE UMSG::CANARY_MAN_MELODY_YES
OBJ_STOP

@nokill:
OBJ_DIALOGUE UMSG::CANARY_MAN_BABY_YES
OBJ_YESNO_IS_NO @no-OBJ_NKR_BOSS
OBJ_DIALOGUE UMSG::CANARY_MAN_MELODY_NO
OBJ_BATTLE (BATTLE_NKRSMONST-BATTLES_START)/$A
OBJ_SET_FLAG $f6
OBJ_SUBROUTINE obj_bossfinisher_subr, 0
OBJ_STOP
    @no:
OBJ_DIALOGUE UMSG::CANARY_MAN_MELODY
    @end:
OBJ_STOP

OBJ_NKR_BOSS_FLAME:
objectDef OBJ_TYPE::STATIONARY_NPC_CHECKSPAWN, 7, DIRECTIONS::UP, $c2
.addr SPRITEDEF_FLAME ;sprite
OBJ_FLAG_DISAPPEAR $f6
    @end:
OBJ_STOP

OBJ_NKR_EXIT:
objectDef OBJ_TYPE::DOOR, 1, DIRECTIONS::LEFT, $c6
doorArgDef 7, $25, DIRECTIONS::DOWN, $a5